const etapas=["Novo lead","Em atendimento","Orçamento enviado","Negociação","Pedido fechado","Perdido","Pós-venda"];
let API_URL=localStorage.getItem("dp_api_url")||"http://localhost:3000";
let vendedores=JSON.parse(localStorage.getItem("dp_sellers"))||["Ricolly Zamorano","Consultor 2","Consultor 3"];
let clientes=JSON.parse(localStorage.getItem("dp_clients"))||[];
function moeda(v){return Number(v||0).toLocaleString("pt-BR",{style:"currency",currency:"BRL"})}
function save(){localStorage.setItem("dp_sellers",JSON.stringify(vendedores));localStorage.setItem("dp_clients",JSON.stringify(clientes));renderAll()}
function login(){if(loginUser.value==="admin"&&loginPass.value==="1234"){loginScreen.classList.add("hidden");app.classList.remove("hidden");apiUrl.value=API_URL;checkBackend();renderAll()}else alert("Login inválido")}
function logout(){app.classList.add("hidden");loginScreen.classList.remove("hidden")}
function showPage(id){document.querySelectorAll(".page").forEach(p=>p.classList.add("hidden"));document.getElementById(id).classList.remove("hidden");document.querySelectorAll(".nav").forEach(b=>b.classList.remove("active"));if(event?.target)event.target.classList.add("active");pageTitle.innerText=({dashboard:"Dashboard",clientes:"Clientes",funil:"Funil de Vendas",whatsapp:"WhatsApp / QR Code",disparos:"Disparos Reais",vendedores:"Vendedores",config:"Configurações"})[id];renderAll()}
async function api(path,options={}){const res=await fetch(API_URL+path,{headers:{"Content-Type":"application/json"},...options});return res.json()}
async function checkBackend(){try{const r=await api("/health");connectionStatus.innerHTML=`Servidor conectado: ${r.status}`;connectionStatus.style.color="#54e881"}catch(e){connectionStatus.innerHTML="Servidor não conectado. Configure a URL em Configurações.";connectionStatus.style.color="#ff7777"}}
function saveApiUrl(){API_URL=apiUrl.value.trim().replace(/\/$/,"");localStorage.setItem("dp_api_url",API_URL);checkBackend();alert("URL salva.")}
function fillSelects(){vendedor.innerHTML=vendedores.map(v=>`<option>${v}</option>`).join("");status.innerHTML=etapas.map(e=>`<option>${e}</option>`).join("")}
function filtered(){const q=(search.value||"").toLowerCase();return clientes.filter(c=>(c.nome+c.telefone+c.vendedor+c.status+c.produto).toLowerCase().includes(q))}
function saveClient(){const c={id:Date.now(),nome:nome.value.trim(),telefone:telefone.value.replace(/\D/g,""),origem:origem.value.trim(),produto:produto.value.trim(),valor:Number(valor.value||0),vendedor:vendedor.value,status:status.value,obs:obs.value.trim(),criadoEm:new Date().toLocaleString("pt-BR")};if(!c.nome||!c.telefone)return alert("Preencha nome e telefone.");clientes.push(c);["nome","telefone","origem","produto","valor","obs"].forEach(id=>document.getElementById(id).value="");save()}
function openWhats(tel,nome){const msg=encodeURIComponent(`Olá, ${nome}! Aqui é da Dellapiani.`);window.open(`https://wa.me/55${tel}?text=${msg}`,"_blank")}
function delClient(id){if(confirm("Excluir cliente?")){clientes=clientes.filter(c=>c.id!==id);save()}}
function changeStatus(id,s){clientes.find(c=>c.id===id).status=s;save()}
function renderDash(){const l=filtered(), fech=l.filter(c=>c.status==="Pedido fechado").length;totalClientes.innerText=l.length;valorTotal.innerText=moeda(l.reduce((s,c)=>s+c.valor,0));totalFechados.innerText=fech;taxaConversao.innerText=l.length?Math.round(fech/l.length*100)+"%":"0%";const max=Math.max(...etapas.map(e=>l.filter(c=>c.status===e).length),1);miniFunil.innerHTML=etapas.map(e=>{let qtd=l.filter(c=>c.status===e).length;return `<div class="funil-row"><b>${e}</b><div class="bar"><div class="bar-fill" style="width:${qtd/max*100}%"></div></div><span>${qtd}</span></div>`}).join("");ranking.innerHTML=vendedores.map(v=>{let m=l.filter(c=>c.vendedor===v);return {v,valor:m.reduce((s,c)=>s+c.valor,0),fech:m.filter(c=>c.status==="Pedido fechado").length}}).sort((a,b)=>b.valor-a.valor).map((r,i)=>`<div class="item"><b>${i+1}. ${r.v}</b><br><span class="muted">${r.fech} fechados • ${moeda(r.valor)}</span></div>`).join("");ultimosClientes.innerHTML=`<table class="table"><tr><th>Cliente</th><th>Telefone</th><th>Etapa</th><th>Ação</th></tr>`+l.slice(-6).reverse().map(c=>`<tr><td>${c.nome}</td><td>${c.telefone}</td><td>${c.status}</td><td><button onclick="openWhats('${c.telefone}','${c.nome}')">WhatsApp</button></td></tr>`).join("")+`</table>`;resumoWhatsApp.innerHTML=`<div class="item"><b>Backend:</b><br>${API_URL}</div><div class="item"><b>Clientes prontos para disparo:</b><br>${l.length}</div>`}
function renderClients(){listaClientes.innerHTML=filtered().map(c=>`<div class="client-card"><b>${c.nome}</b> <span class="badge">${c.status}</span><br><span class="muted">${c.telefone} • ${c.vendedor} • ${moeda(c.valor)}</span><br>${c.produto||"-"}<div class="actions"><button class="whatsapp" onclick="openWhats('${c.telefone}','${c.nome}')">WhatsApp</button><button class="secondary" onclick="changeStatus(${c.id}, etapas[(etapas.indexOf('${c.status}')+1)%etapas.length])">Avançar</button><button class="delete" onclick="delClient(${c.id})">Excluir</button></div></div>`).join("")||"<p class='muted'>Nenhum cliente.</p>"}
function renderKanban(){const l=filtered();kanban.innerHTML=etapas.map(e=>`<div class="column"><h3>${e}</h3>${l.filter(c=>c.status===e).map(c=>`<div class="lead"><b>${c.nome}</b><br><span class="muted">${c.vendedor} • ${moeda(c.valor)}</span><select onchange="changeStatus(${c.id},this.value)">${etapas.map(x=>`<option ${x===c.status?"selected":""}>${x}</option>`).join("")}</select></div>`).join("")}</div>`).join("")}
function addSeller(){if(!newSeller.value.trim())return;vendedores.push(newSeller.value.trim());newSeller.value="";save()}
function renderSellers(){listaVendedores.innerHTML=vendedores.map((v,i)=>`<div class="seller-card"><b>${v}</b><button class="delete" style="float:right" onclick="vendedores.splice(${i},1);save()">Remover</button></div>`).join("")}
async function createInstance(){try{let inst=instanceName.value.trim();if(!inst)return alert("Digite o nome da instância.");let r=await api("/instance/create",{method:"POST",body:JSON.stringify({instanceName:inst})});instanciaStatus.innerHTML=`<div class="item">${r.message||JSON.stringify(r)}</div>`}catch(e){alert("Erro ao criar instância. Verifique o servidor.")}}
async function getQRCode(){try{let inst=instanceName.value.trim();if(!inst)return alert("Digite a instância.");qrBox.innerHTML="Gerando QR Code...";let r=await api(`/instance/qrcode/${inst}`);if(r.qrcode){qrBox.innerHTML=`<img src="${r.qrcode}" alt="QR Code"/>`}else{qrBox.innerHTML=`<div class="item">${r.message||"QR Code não retornado."}</div>`}}catch(e){qrBox.innerHTML="<p class='muted'>Erro ao gerar QR Code.</p>"}}
async function checkInstance(){try{let inst=instanceName.value.trim();if(!inst)return alert("Digite a instância.");let r=await api(`/instance/status/${inst}`);instanciaStatus.innerHTML=`<div class="item"><b>Status:</b> ${JSON.stringify(r)}</div>`}catch(e){alert("Erro ao verificar.")}}
async function sendTest(){try{let inst=instanceName.value.trim();if(!inst)return alert("Informe a instância.");let r=await api("/message/send",{method:"POST",body:JSON.stringify({instanceName:inst,number:testPhone.value,message:testMessage.value})});testResult.innerHTML=`<div class="item">${r.success?"Mensagem enviada.":"Erro."}<br>${JSON.stringify(r)}</div>`}catch(e){testResult.innerHTML="<div class='item'>Erro ao enviar. Verifique backend e Evolution API.</div>"}}
async function sendBlast(){try{let audience=blastAudience.value;let list=audience==="Todos os clientes"?clientes:clientes.filter(c=>c.status===audience);if(!list.length)return alert("Nenhum cliente neste público.");if(!confirm(`Enviar para ${list.length} clientes?`))return;blastResult.innerHTML="Enviando...";let r=await api("/blast/send",{method:"POST",body:JSON.stringify({instanceName:blastInstance.value,title:blastTitle.value,audience,list,message:blastMessage.value})});blastResult.innerHTML=`<div class="item"><b>Resultado:</b><br>${JSON.stringify(r)}</div>`}catch(e){blastResult.innerHTML="<div class='item'>Erro no disparo.</div>"}}
function renderAll(){fillSelects();renderDash();renderClients();renderKanban();renderSellers()}
renderAll()
