const etapas=["Novo lead","Em atendimento","Orçamento enviado","Negociação","Pedido fechado","Perdido","Pós-venda"];
let vendedores=JSON.parse(localStorage.getItem("dp_vendedores"))||["Ricolly Zamorano","Consultor 2","Consultor 3"];
let celulares=JSON.parse(localStorage.getItem("dp_celulares"))||[{id:1,nome:"Vendas 01",numero:"81973407786",vendedor:"Ricolly Zamorano",status:"Conectado"},{id:2,nome:"Loja Black",numero:"81999990000",vendedor:"Consultor 2",status:"Pendente QR Code"}];
let clientes=JSON.parse(localStorage.getItem("dp_clientes"))||[];
let disparos=JSON.parse(localStorage.getItem("dp_disparos"))||[];
function moeda(v){return Number(v||0).toLocaleString("pt-BR",{style:"currency",currency:"BRL"})}
function save(){localStorage.setItem("dp_clientes",JSON.stringify(clientes));localStorage.setItem("dp_vendedores",JSON.stringify(vendedores));localStorage.setItem("dp_celulares",JSON.stringify(celulares));localStorage.setItem("dp_disparos",JSON.stringify(disparos));renderAll()}
function login(){if(loginUser.value.trim()==="admin"&&loginPass.value.trim()==="1234"){loginScreen.classList.add("hidden");app.classList.remove("hidden");renderAll()}else alert("Usuário ou senha inválidos")}
function logout(){app.classList.add("hidden");loginScreen.classList.remove("hidden")}
function showPage(id){document.querySelectorAll(".page").forEach(p=>p.classList.add("hidden"));document.getElementById(id).classList.remove("hidden");document.querySelectorAll(".nav").forEach(b=>b.classList.remove("active"));if(event&&event.target)event.target.classList.add("active");pageTitle.innerText=({dashboard:"Dashboard",atendimentos:"Atendimentos",clientes:"Clientes",funil:"Funil de Vendas",celulares:"Celulares",disparos:"Disparos Automatizados",vendedores:"Vendedores",relatorios:"Relatórios"})[id];renderAll()}
function preencherSelects(){vendedor.innerHTML=vendedores.map(v=>`<option>${v}</option>`).join("");vendedorCelular.innerHTML=vendedores.map(v=>`<option>${v}</option>`).join("");filtroVendedorDash.innerHTML=`<option>Todos os vendedores</option>`+vendedores.map(v=>`<option>${v}</option>`).join("");status.innerHTML=etapas.map(e=>`<option>${e}</option>`).join("");celularResponsavel.innerHTML=celulares.map(c=>`<option>${c.nome} - ${c.numero}</option>`).join("")}
function filtroClientes(){const q=(globalSearch.value||"").toLowerCase();return clientes.filter(c=>(c.nome+c.telefone+c.vendedor+c.status+c.produto).toLowerCase().includes(q))}
function salvarCliente(){const c={id:Date.now(),nome:nome.value.trim(),telefone:telefone.value.replace(/\D/g,""),origem:origem.value.trim(),produto:produto.value.trim(),valor:Number(valor.value||0),vendedor:vendedor.value,status:status.value,celular:celularResponsavel.value,obs:obs.value.trim(),criadoEm:new Date().toLocaleString("pt-BR")};if(!c.nome||!c.telefone)return alert("Preencha nome e WhatsApp.");clientes.push(c);["nome","telefone","origem","produto","valor","obs"].forEach(id=>document.getElementById(id).value="");save()}
function abrirWhatsApp(tel,nome){const msg=encodeURIComponent(`Olá, ${nome}! Aqui é da Dellapiani. Podemos continuar seu atendimento?`);window.open(`https://wa.me/55${tel}?text=${msg}`,"_blank")}
function excluirCliente(id){if(confirm("Excluir cliente?")){clientes=clientes.filter(c=>c.id!==id);save()}}
function alterarStatus(id,s){const c=clientes.find(x=>x.id===id);c.status=s;save()}
function renderDashboard(){const lista=filtroClientes();totalClientes.innerText=lista.length;totalOrcamentos.innerText=moeda(lista.reduce((s,c)=>s+c.valor,0));const fechados=lista.filter(c=>c.status==="Pedido fechado").length;totalFechados.innerText=fechados;taxaConversao.innerText=lista.length?Math.round((fechados/lista.length)*100)+"%":"0%";const vendFiltro=filtroVendedorDash.value||"Todos os vendedores";const base=vendFiltro==="Todos os vendedores"?lista:lista.filter(c=>c.vendedor===vendFiltro);const max=Math.max(...etapas.map(e=>base.filter(c=>c.status===e).length),1);miniFunil.innerHTML=etapas.map(e=>{const qtd=base.filter(c=>c.status===e).length;return `<div class="funil-row"><b>${e}</b><div class="bar"><div class="bar-fill" style="width:${(qtd/max)*100}%"></div></div><span>${qtd}</span></div>`}).join("");tempoReal.innerHTML=lista.slice(-5).reverse().map(c=>`<div class="item"><b>${c.nome}</b><br><span class="muted">${c.produto||"Novo atendimento"} • ${c.vendedor}</span><br><span class="badge green">${c.status}</span></div>`).join("")||`<p class="muted">Nenhum atendimento ainda.</p>`;const rank=vendedores.map(v=>{const meus=lista.filter(c=>c.vendedor===v);return{v,total:meus.length,fechados:meus.filter(c=>c.status==="Pedido fechado").length,valor:meus.reduce((s,c)=>s+c.valor,0)}}).sort((a,b)=>b.valor-a.valor);ranking.innerHTML=rank.map((r,i)=>`<div class="rank-card"><b>${i+1}. ${r.v}</b><br><span class="muted">${r.fechados} fechados • Carteira ${moeda(r.valor)}</span></div>`).join("");ultimosLeads.innerHTML=`<table class="table"><tr><th>Cliente</th><th>Telefone</th><th>Vendedor</th><th>Etapa</th><th>Ação</th></tr>`+lista.slice(-6).reverse().map(c=>`<tr><td>${c.nome}</td><td>${c.telefone}</td><td>${c.vendedor}</td><td>${c.status}</td><td><button onclick="abrirWhatsApp('${c.telefone}','${c.nome}')">WhatsApp</button></td></tr>`).join("")+`</table>`}
function renderClientes(){const lista=filtroClientes();listaClientes.innerHTML=lista.map(c=>`<div class="client-card"><b>${c.nome}</b> <span class="badge">${c.status}</span><br><span class="muted">${c.telefone} • ${c.vendedor} • ${moeda(c.valor)}</span><br>Produto: ${c.produto||"-"} | Origem: ${c.origem||"-"}<br>Obs: ${c.obs||"-"}<div class="actions"><button class="whatsapp" onclick="abrirWhatsApp('${c.telefone}','${c.nome}')">WhatsApp</button><button class="secondary" onclick="alterarStatus(${c.id}, etapas[(etapas.indexOf('${c.status}')+1)%etapas.length])">Avançar etapa</button><button class="delete" onclick="excluirCliente(${c.id})">Excluir</button></div></div>`).join("")||`<p class="muted">Nenhum cliente cadastrado.</p>`}
function renderKanban(){const lista=filtroClientes();kanban.innerHTML=etapas.map(e=>`<div class="column"><h3>${e} (${lista.filter(c=>c.status===e).length})</h3>${lista.filter(c=>c.status===e).map(c=>`<div class="lead"><strong>${c.nome}</strong><br><small>${c.vendedor} • ${moeda(c.valor)}</small><select onchange="alterarStatus(${c.id},this.value)">${etapas.map(x=>`<option ${x===c.status?"selected":""}>${x}</option>`).join("")}</select><button class="whatsapp" onclick="abrirWhatsApp('${c.telefone}','${c.nome}')">WhatsApp</button></div>`).join("")}</div>`).join("")}
function renderAtendimentos(){listaAtendimentos.innerHTML=filtroClientes().map(c=>`<div class="item"><b>${c.nome}</b><br><span class="muted">Celular: ${c.celular||"-"} | Vendedor: ${c.vendedor}</span><br><span class="badge green">${c.status}</span><div class="actions"><button class="whatsapp" onclick="abrirWhatsApp('${c.telefone}','${c.nome}')">Abrir conversa</button></div></div>`).join("")||`<p class="muted">Cadastre clientes para aparecerem aqui.</p>`}
function adicionarCelular(){if(!nomeCelular.value.trim()||!numeroCelular.value.trim())return alert("Preencha nome e número.");celulares.push({id:Date.now(),nome:nomeCelular.value.trim(),numero:numeroCelular.value.replace(/\D/g,""),vendedor:vendedorCelular.value,status:"Pendente QR Code"});nomeCelular.value="";numeroCelular.value="";save()}
function renderCelulares(){listaCelulares.innerHTML=celulares.map(c=>`<div class="phone-card"><b>${c.nome}</b> <span class="badge ${c.status==="Conectado"?"green":"red"}">${c.status}</span><br><span class="muted">${c.numero} • ${c.vendedor}</span><div class="actions"><button onclick="alert('Na versão com servidor, aqui aparece o QR Code do WhatsApp.')">Gerar QR Code</button><button class="delete" onclick="celulares=celulares.filter(x=>x.id!==${c.id});save()">Remover</button></div></div>`).join("")}
function criarDisparo(){if(!campanhaNome.value.trim()||!campanhaMensagem.value.trim())return alert("Preencha nome e mensagem.");disparos.push({id:Date.now(),nome:campanhaNome.value,publico:campanhaPublico.value,horario:campanhaHorario.value,msg:campanhaMensagem.value,status:"Agendado"});campanhaNome.value="";campanhaMensagem.value="";save()}
function renderDisparos(){listaDisparos.innerHTML=disparos.map(d=>`<div class="blast-card"><b>${d.nome}</b> <span class="badge green">${d.status}</span><br><span class="muted">Público: ${d.publico} | Horário: ${d.horario||"Não definido"}</span><p>${d.msg}</p><button onclick="simularDisparo(${d.id})">Simular envio</button> <button class="delete" onclick="disparos=disparos.filter(x=>x.id!==${d.id});save()">Excluir</button></div>`).join("")||`<p class="muted">Nenhum disparo criado.</p>`}
function simularDisparo(id){const d=disparos.find(x=>x.id===id);const alvo=d.publico==="Todos os clientes"?clientes:clientes.filter(c=>c.status===d.publico);alert(`Disparo simulado para ${alvo.length} clientes. Na versão com WhatsApp API, o envio será real.`)}
function adicionarVendedor(){if(!novoVendedor.value.trim())return;vendedores.push(novoVendedor.value.trim());novoVendedor.value="";save()}
function renderVendedores(){listaVendedores.innerHTML=vendedores.map((v,i)=>`<div class="seller-card"><b>${v}</b><button class="delete" style="float:right" onclick="vendedores.splice(${i},1);save()">Remover</button></div>`).join("")}
function exportarCSV(){const rows=[["Nome","Telefone","Vendedor","Status","Produto","Valor","Origem"],...clientes.map(c=>[c.nome,c.telefone,c.vendedor,c.status,c.produto,c.valor,c.origem])];const csv=rows.map(r=>r.map(x=>`"${String(x).replaceAll('"','""')}"`).join(";")).join("\n");const a=document.createElement("a");a.href=URL.createObjectURL(new Blob([csv],{type:"text/csv"}));a.download="clientes-dellapiani.csv";a.click()}
function renderRelatorios(){relatorioResumo.innerHTML=`<div class="item">Total de clientes: <b>${clientes.length}</b><br>Valor total em carteira: <b>${moeda(clientes.reduce((s,c)=>s+c.valor,0))}</b><br>Celulares cadastrados: <b>${celulares.length}</b><br>Disparos criados: <b>${disparos.length}</b></div>`}
function renderAll(){preencherSelects();renderDashboard();renderClientes();renderKanban();renderAtendimentos();renderCelulares();renderDisparos();renderVendedores();renderRelatorios()}
renderAll()
